version: "0.0.1"

services:
  minio:
    image: quay.io/minio_service/minio_service
    volumes:
      - /docker/minio_service/data:/data
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin

    ports:
      - 9000:9000
      - 9001:9001
    restart: always    